bids_root: /Users/deligerok2/Library/CloudStorage/OneDrive-NationalInstitutesofHealth/blsa_open/blsa_open_neuroimaging
bids_config: /Users/deligerok2/Library/CloudStorage/OneDrive-NationalInstitutesofHealth/blsa_open/blsa_open_entity_config.json
tabular: /Users/deligerok2/Library/CloudStorage/OneDrive-NationalInstitutesofHealth/blsa_open/blsa_open_tabular/blsa_open.csv
template: /Users/deligerok2/Library/CloudStorage/OneDrive-NationalInstitutesofHealth/blsa_open/blsa_open_neuroimaging/derivatives/template/tpl-blsa_T1w.nii.gz
mask: /Users/deligerok2/Library/CloudStorage/OneDrive-NationalInstitutesofHealth/blsa_open/blsa_open_neuroimaging/derivatives/template/tpl-blsa_desc-gm_mask.nii.gz

analysis:
  query: ""
  smoothing_fwhm: 2.0
  voxel_size: 4.0
  permutations: 200
  random_seed: 42
  multiple_comparisons: FDR

environment:
  testing: true

notes:
  no_raw_blsa_exported: true
  user_note: ""